wip

diff --git a/src/go b/src/go
--- a/src/go
+++ b/src/go
@@ -37,15 +37,17 @@ cmake -S .  -B  ../src.build
 [ $? != 0 ] && exit -1
 cmake  --build ../src.build/ 
 [ $? != 0 ] && exit -1
-pushd ../src.build/ut
-./krunchercoreut
-if [ $? != 0 ]; then
-	echo -ne "\033[31mTest failed\033[0m\n"  
-	exit -1 
-else
-	echo -ne "\033[32mTest succeeded\033[0m\n"
+if [ "${1}" == "-test" ]; then 
+	pushd ../src.build/ut
+	./krunchercoreut
+	if [ $? != 0 ]; then
+		echo -ne "\033[31mTest failed\033[0m\n"  
+		exit -1 
+	else
+		echo -ne "\033[32mTest succeeded\033[0m\n"
+	fi
+	popd
 fi
-popd
 
 [ "${1}" == "-install" ] &&  sudo cmake --install ../src.build
 
